version: '3'
services:
  eureka-service:
    container_name: eureka-service
    build:
      context: ./
      dockerfile: Dockerfile
    image: devilmustcry/microservice-eureka-server:0.1
    restart: always
    expose: 
      - 8888
    ports:
      - 8888:8888
